//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhaTro
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDichVu
    {
        public int MaChiTietDV { get; set; }
        public Nullable<System.DateTime> NgaySuDung { get; set; }
        public int MaDV { get; set; }
        public int MaChiTietHD { get; set; }
    
        public virtual ChiTietHopDong ChiTietHopDong { get; set; }
        public virtual DichVu DichVu { get; set; }
    }
}
