//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhaTro
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachHang()
        {
            this.HopDongThues = new HashSet<HopDongThue>();
        }
    
        public int MaKhach { get; set; }
        public string TenKhach { get; set; }
        public Nullable<int> CMND { get; set; }
        public string GioiTinh { get; set; }
        public string DiaChiKhach { get; set; }
        public string NgheNghiep { get; set; }
        public Nullable<decimal> SdtKhach { get; set; }
        public byte[] HinhAnhKH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HopDongThue> HopDongThues { get; set; }
    }
}
