//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhaTro
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhongTro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhongTro()
        {
            this.ChiTietHopDongs = new HashSet<ChiTietHopDong>();
            this.TrangBis = new HashSet<TrangBi>();
        }
    
        public int MaPhong { get; set; }
        public string TenPhong { get; set; }
        public Nullable<int> SoLuongNguoi { get; set; }
        public int MaLoaiPhong { get; set; }
        public int MaNhaTro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHopDong> ChiTietHopDongs { get; set; }
        public virtual LoaiPhong LoaiPhong { get; set; }
        public virtual NhaTro NhaTro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrangBi> TrangBis { get; set; }
    }
}
